server:
  port: 8800

spring:
  profiles:
    active: default

#This configuration is disabled because the routes will be configured in Java class./
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: service-one
#        uri: http://localhost:8890/
#        predicates:
#        - Path=/serviceone/**
#      - id: service-two
#        uri: http://localhost:8891/
#        predicates:
#        - Path=/servicetwo/**